name: Deployment pipeline

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      with:
        fetch-depth: 0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.0
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Run linter validation
      run: npm run eslint
    - name: Deploy to heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health"
          rollbackonhealthcheckfailed: true