name: Deployment pipeline

on:
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      with:
        fetch-depth: 0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.0
      with:
        node-version: 16
    - name: Install dependencies
      run: npm i
    - name: Run linter validation
      run: npm run eslint
    - name: Cypress.io
      uses: cypress-io/github-action@v4.2.0
      with:
          start: npm run start-test
          command: npm run test:e2e
          wait-on: http://localhost:5000