name: Deployment pipeline

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize


jobs:
  avoid_redundancy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel redundant builds
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{github.token}}
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run linter validation
        run: npm run eslint
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      with:
        fetch-depth: 0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.0
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: dist
        path: dist

  tests:
    needs:
     - lint
     - build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      with:
        fetch-depth: 0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.0
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - uses: actions/download-artifact@v3.0.0
      with:
        name: dist
        path: dist
    - name: Test
      run: npm run test
  deploy:
    needs:
      - tests
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      with:
        fetch-depth: 0
    - name: Deploy to heroku
      if: ${{github.event_name == 'push'}}
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health"
          rollbackonhealthcheckfailed: true